# CTFd Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctfd
  namespace: ctfd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: ctfd.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ctfd-main
                port:
                  number: 8000
---

